version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: moa-backend-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=moa_agriplan_system.settings
      - DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=moa_production
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db-prod
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-88#b%1&6ku6g#eyb04)vd1)h5!)*y^79havgg(**w65ewhv+ln
      - ALLOWED_HOSTS=localhost,127.0.0.1,10.10.20.233,196.188.248.104
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://10.10.20.233:3000,http://10.10.20.233:8080,http://196.188.248.104:8080
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://10.10.20.233:3000,http://10.10.20.233:8080,http://196.188.248.104:8080
    depends_on:
      - db-prod

  frontend:
    build:
      context: ./frontend/planning-vite
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://196.188.248.104:8080
    container_name: moa-frontend-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  db-prod:
    image: postgres:16-alpine
    container_name: moa-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: moa_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db_prod_data:
